image: go1.3
env:
  - GOPATH=/var/cache/drone
services:
  - redis
  - apcera/gnatsd
  - dockerfile/rethinkdb
script:
  - go get -t -v ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - GOMAXPROCS=4 go test -v github.com/lavab/api/setup
  - GOMAXPROCS=4 go test -v -covermode=count -coverprofile=coverage.out github.com/lavab/api/routes
  - /var/cache/drone/bin/goveralls -coverprofile=coverage.out -service=lavadrone -repotoken $COVERALLS_TOKEN
notify:
  slack:
   - webhook_url: $$SLACK_URL
   - channel: integration
   - username: lavadrone
   - on_started: true
   - on_success: true
   - on_failure: true