image: registry.lavaboom.io/lavaboom/wrapper
env:
  - GOPATH=/var/cache/drone
services:
  - redis
  - apcera/gnatsd
  - dockerfile/rethinkdb
script:
  - pip install fabric
  - go get -t -v ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - GOMAXPROCS=4 go test -v github.com/lavab/api/setup
  - GOMAXPROCS=4 go test -v -covermode=count -coverprofile=coverage.out github.com/lavab/api/routes
  - /var/cache/drone/bin/goveralls -coverprofile=coverage.out -service=lavadrone -repotoken $COVERALLS_TOKEN
  - "if [ \"$DRONE_BRANCH\" = \"master\" ]; then fab -H marge.lavaboom.io:36104 deploy; fi"
  - "if [ \"$DRONE_BRANCH\" = \"staging\" ]; then fab -H lisa.lavaboom.io:36412 deploy; fi"
  - "if [ \"$DRONE_BRANCH\" = \"develop\" ]; then fab -H bart.lavaboom.io:36467 deploy; fi"
notify:
  slack:
   - webhook_url: $$SLACK_URL
   - channel: $$SLACK_CHANNEL
   - username: lavadrone
   - on_started: true
   - on_success: true
   - on_failure: true