image: go1.3
env:
  - GOPATH=/var/cache/drone
services:
  - redis
  - apcera/gnatsd
  - dockerfile/rethinkdb
script:
  - go get -t -v ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - GOMAXPROCS=4 go test -v github.com/lavab/api/setup
  - GOMAXPROCS=4 go test -v -covermode=count -coverprofile=coverage.out github.com/lavab/api/routes
  - /var/cache/drone/bin/goveralls -coverprofile=coverage.out -service=lavadrone -repotoken $COVERALLS_TOKEN
  - "if [ \"$DRONE_BRANCH\" = \"master\" ]; then export CONTAINER_NAME=api-master; export CONTAINER_PORT=10000; fi"
  - "if [ \"$DRONE_BRANCH\" = \"develop\" ]; then export CONTAINER_NAME=api-develop; export CONTAINER_PORT=10001; fi"
  - "if [ -n $DRONE_BRANCH ]; then ssh -p 36412 root@lisa.lavaboom.io \"/opt/deploy/$CONTAINER_NAME.sh\"; fi"
notify:
  slack:
   - webhook_url: $$SLACK_URL
   - channel: $$SLACK_CHANNEL
   - username: lavadrone
   - on_started: true
   - on_success: true
   - on_failure: true